apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: ghcr.io/anicord-acow/frontend@sha256:777e973d8fba58532b9a52b5fe42b8dcbb46abd9512608059d7817a77304075d
        ports:
        - containerPort: 3000
        env:
        - name: API_ORIGIN
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: API_ORIGIN
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 13003
  selector:
    app: frontend
