apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: ghcr.io/anicord-acow/frontend@sha256:2ee0c0bfd09107ca0915f1435cf445da9cbe89088e41346554ed9dfd21ea3591
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: API_ORIGIN
        - name: ORIGIN
          value: "https://anidev.cestpaspete.ovh"
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 13003
  selector:
    app: frontend
