apiVersion: v1
kind: Namespace
metadata:
  name: anidev-webserver
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    pod-security.kubernetes.io/enforce: baseline

---

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-namespace"
  namespace: anidev-webserver
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - backend
          - frontend
          - mariadb
          - redis
  egress:
    - toEndpoints:
        - matchLabels: {} # Allows communication between pods in the same namespace
