apiVersion: v1
kind: Secret
metadata:
    name: webserver-secrets
    namespace: webserver
type: Opaque
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:Qi/IDVgeb8iKn2sI2+N4gHDpPGpie5Ma9Sc2PktF,iv:dJILwD86O77MEHvvj+LYdPVCrDk2weC0jm6WTBuIP7s=,tag:ZBW3Z/75kmqiVeYtIpttJw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:dHJSmS4Xc7PCiw==,iv:RrtDl+Maim5tjT2eppcqkX3HVAHlSjrOgDUkRpo+sPk=,tag:WGZm/2hWmkyigMOEB26D1g==,type:str]
    mariadb-user: ENC[AES256_GCM,data:GxTfgqmL68rmXkc50rXE,iv:LCX1I4ICNwKyxL02Cs5W2stwjkGFe0f8XFWafBH+a5A=,tag:ggmJDzirCmOv2JP0B71Mqw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:bD+p7Iplto6O/Gq8cowwBNbvjyj0WhkeRgsR9hAt,iv:DaSlY/tnjYDnldNHSoux7+RqwGB0mlY5/uUIKo6OJYM=,tag:lMlVcfg1cZBEV2Oq0lmepg==,type:str]
sops:
    age:
        - recipient: age12qymzd9yg0w68wwfyfrhsc2r5zkxxzp8a4yck960xp9uxsvmwchqyzj8lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRlBDTXN1UFhyUnE0UmhE
            VnZac2ptQ2Z1dTNTeDR6UzFzcFhMeCtsNFhZCnFlcERNRlJCU3NIYitIRThnSWw1
            UDcrRG1nVi9ZcUIvSkl2MmNodXFxQzQKLS0tIGsrNnI5ZzlZMXI3YnVoNG5IU0k0
            UG5GeXlIbnRaL3hhcEE1czl4M0JCdzAKj4zV1nRpPQga7eeM4fVXKOLRLkIm3cf3
            Uk62vI3zJQNMbHaLYPPfFPoJVCPtjU6Lk1+1RZ0C4zvye37jcnQSIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T20:28:55Z"
    mac: ENC[AES256_GCM,data:bUdhMfTUJsUilXl+ZPMV9SMzD8fo13hH83Akg2BMW2eovQ9M7o4/DVwCC1qJcMUA+6CulkxfInOd1fXs/NkbzBJA8Do02xWNAGuYpgNTxy/xeIrKGUFr9+l3X2GJ4h5G/q3KjZCM/+z8xCeknznO2va5Y1Mxi4PbW4tIe9XCi9o=,iv:4nqj6jt0H9lgxgDk2YV8+LhefRwUqwNGct/Xvz9fVy4=,tag:zy2IXVUcvoJW3WK9E4bIfw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: webserver
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:qysppxMpiYbecgdxRAF6DgU1Re+bQmt8RtIkQCVoNpf8LY84f66bCSbPdIGAYuGhaliXGro9C5ryT1IGaN8RTVrxt0C2cKtEPaAurAAdAMevC7I5qjIO2Moxw9kZ0zy4xWK/LaHck1WW6He9wD1frZ7nTmiKbrK43O6iZAAZAE3rUlvkfg==,iv:ZK1AA3SW5wZs3QQqwLts4BtyCui9fLSJRHEmjziAqfQ=,tag:VcLOf42wmV6SD73QKsGWAA==,type:str]
sops:
    age:
        - recipient: age12qymzd9yg0w68wwfyfrhsc2r5zkxxzp8a4yck960xp9uxsvmwchqyzj8lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRlBDTXN1UFhyUnE0UmhE
            VnZac2ptQ2Z1dTNTeDR6UzFzcFhMeCtsNFhZCnFlcERNRlJCU3NIYitIRThnSWw1
            UDcrRG1nVi9ZcUIvSkl2MmNodXFxQzQKLS0tIGsrNnI5ZzlZMXI3YnVoNG5IU0k0
            UG5GeXlIbnRaL3hhcEE1czl4M0JCdzAKj4zV1nRpPQga7eeM4fVXKOLRLkIm3cf3
            Uk62vI3zJQNMbHaLYPPfFPoJVCPtjU6Lk1+1RZ0C4zvye37jcnQSIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T20:28:55Z"
    mac: ENC[AES256_GCM,data:bUdhMfTUJsUilXl+ZPMV9SMzD8fo13hH83Akg2BMW2eovQ9M7o4/DVwCC1qJcMUA+6CulkxfInOd1fXs/NkbzBJA8Do02xWNAGuYpgNTxy/xeIrKGUFr9+l3X2GJ4h5G/q3KjZCM/+z8xCeknznO2va5Y1Mxi4PbW4tIe9XCi9o=,iv:4nqj6jt0H9lgxgDk2YV8+LhefRwUqwNGct/Xvz9fVy4=,tag:zy2IXVUcvoJW3WK9E4bIfw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
