apiVersion: v1
kind: Secret
metadata:
    name: webserver-secrets
    namespace: anicord-webserver
type: Opaque
stringData:
    MYSQL: ENC[AES256_GCM,data:fv2vipzIq1RaeemtTe/bEMPa8HHcIZCLmeH+HsuF2E1hehh1fyub5vLQxIGhN5qMN8jvI4pG3b61GOwivxZXiZEbBymZM1nJZQ==,iv:/kQ4jncuKGPHn8tYtYct1tmqABMBhBUyYbdU1RNWAls=,tag:Zhuh2iEvHdXZB6DirxmYZg==,type:str]
    REDIS: ENC[AES256_GCM,data:gKHaNSYw3nw13SXsfh2Ijn5p9fCj+Y0TY8wm0A6I6x3gXhyXGMTXI3rbbEwA3Haq5RQ=,iv:QJposdbomYh9Sxs24t1NMA6ypGmCSsheYNMM611fr0Y=,tag:KSKzIQQVEZS9nOtwVaL4vA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:hgv5I5voch6g73Nos4tmsCskfF3m5lYGrLdNbVjv,iv:lOq1r0ZTWIEtdiQEzMfp0EZ19m+sPJ5qHCHxdaw/M7Q=,tag:B6FJz1HTlyX0103ZlTMC7g==,type:str]
    mariadb-database: ENC[AES256_GCM,data:ujaROsMNh7QoFw==,iv:jUxU8ldRpQzo/OpGDcQf5oOFctz6ylHt5VVPOH7kZHU=,tag:Pid+dtb2ONpmDIM0Q1ibyg==,type:str]
    mariadb-user: ENC[AES256_GCM,data:Qyme0RPN8sA4xQ==,iv:mTcJNEZkqonmOFxvnZGpXX2mDw4hi/E2OwDXTu8PdQY=,tag:k4HQzghxxI0oDm4ZplGOfA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:d0wp4JRLO/1EtM7+LkUQQDpfi1dAjfkOeCh6Dpw8,iv:jzfWEO0hYPlsYA9zVS6YpZQAY0zw4GqxtUgEGMgLXo0=,tag:LqBgNRyCKb2/QiFtIxwDiw==,type:str]
    redis-password: ENC[AES256_GCM,data:GAp+z2M30C+HOjRDqGIOlTjMkynw/UEkiFtVGJu6,iv:QmVvN6AdFWidPweuSky2hWkLKz0jq9EJcRLltyMXJYI=,tag:qltVXRk9fko6aDMKPeKLSA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Oyz4TMQQuFTg3ooz6rPnHXn8Jy5+glmve2XZ8pPVBg1ZEqPLvcBYvZYaU8RLdN7GCGJpDZIql6cla91yJZmdqw==,iv:ujmF4gEuH6m2ustCRxwQ5bd28bN0W3YWL+7wGvfeXD4=,tag:DfNYDKqJKkwDa4D63FmaDw==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:M2O+kNIns+NgoEiyzxGGC0yKhg==,iv:os9oak8bxp+tt6l4VXbUxanlReq2jk9rlh7VUf1fjS4=,tag:/vGXZh2wbkHT2mQXS65fLw==,type:int]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:/P+VDcLDdD5u/jxSz/U/kCLyYUaaSGAIM5AVzGvjfVo=,iv:6X7cv/9V75fmnZdeKMjte4LUUBzo/wUj7B3luaBbHjY=,tag:/DsEvZ+86agJc9Nu3bnWoA==,type:str]
sops:
    age:
        - recipient: age12qymzd9yg0w68wwfyfrhsc2r5zkxxzp8a4yck960xp9uxsvmwchqyzj8lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UTN5SUN1dTgxbmRSVmFt
            dVY1TE9ybUpubGYrN0t0bVNmK2pucUdVWWlRCmZ3bk1CRXRib251VzkwUzdIU2xu
            cmJWekpseEd3aDFURWVzSGdtWXcxY0UKLS0tIFpjby9DOURCbW9Ib0VzRnhtM09k
            UVlzbUlSY0J5M2U0REpKR2dvVDNLUW8KfycgoW27kgnD58TwWsRPooROd/nwEJxZ
            9N2l5iTJjgrFtni7s+vtuPykhQnkvvSNMtSqUVMI6LkqiWOn3Yk/CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T12:53:58Z"
    mac: ENC[AES256_GCM,data:GiTQLS2+9AUt+6Db4eXGd3wTHtvPD0gYXsn+hYs9xXxbiempqTfixMw13Tde5Daxx/EZiR9XXJQEAxaXMcxCAMWKH9OY8vaCxEe8hEYowQ9qN+oneajQfuPgRG9vN3ot2/8V3CuycIqSGuZK6ooE3kBYMGEEMs8OWoVmzr4czeI=,iv:8zK+0HS0wJIUz2TqSwgeimrJm6AuQT5TE3n8npPzizQ=,tag:GBwGuvhnyTpfJmJANVhqFg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: anicord-webserver
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Bl7HhTY1ol5/myHlJE9/BiPdVPIB6OLaH0MT0suHHpZrCAWAQP6RtXIDUSXbUP/UO80trvwX9KoUZJf2I0ak7ekZkhc7ryq7yV7jrP5uYocqg6bLCZHmM4YsbyixyE+2YWaY5gd/ib72W5KAf8ivrC77av+IQNBdj+z6J+RXfJjhBACU9g==,iv:HhcwdmSskC68EG7LPt2yD15/PS3HjjXZrGEEKVvyFho=,tag:UA7AZlkfs3aDCKfNUPsudg==,type:str]
sops:
    age:
        - recipient: age12qymzd9yg0w68wwfyfrhsc2r5zkxxzp8a4yck960xp9uxsvmwchqyzj8lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UTN5SUN1dTgxbmRSVmFt
            dVY1TE9ybUpubGYrN0t0bVNmK2pucUdVWWlRCmZ3bk1CRXRib251VzkwUzdIU2xu
            cmJWekpseEd3aDFURWVzSGdtWXcxY0UKLS0tIFpjby9DOURCbW9Ib0VzRnhtM09k
            UVlzbUlSY0J5M2U0REpKR2dvVDNLUW8KfycgoW27kgnD58TwWsRPooROd/nwEJxZ
            9N2l5iTJjgrFtni7s+vtuPykhQnkvvSNMtSqUVMI6LkqiWOn3Yk/CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T12:53:58Z"
    mac: ENC[AES256_GCM,data:GiTQLS2+9AUt+6Db4eXGd3wTHtvPD0gYXsn+hYs9xXxbiempqTfixMw13Tde5Daxx/EZiR9XXJQEAxaXMcxCAMWKH9OY8vaCxEe8hEYowQ9qN+oneajQfuPgRG9vN3ot2/8V3CuycIqSGuZK6ooE3kBYMGEEMs8OWoVmzr4czeI=,iv:8zK+0HS0wJIUz2TqSwgeimrJm6AuQT5TE3n8npPzizQ=,tag:GBwGuvhnyTpfJmJANVhqFg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
