apiVersion: v1
kind: Secret
metadata:
    name: webserver-secrets
    namespace: anicord-webserver
type: Opaque
stringData:
    MYSQL: ENC[AES256_GCM,data:REzzA8V/5SsRCjGjBayQaUxU3pG1jz12pHJaoI6L4svTqSaGpKwvYNypOPz6csFbu8svfFb3qPp2aDhwUhvzBeaY1ChIFuGa3g==,iv:PsSw2+J7otXa38cjYQLkbH2YS7xZYvqBxpqANyZv3EA=,tag:L0HKVk2CwsU/y9+6zD2sLw==,type:str]
    REDIS: ENC[AES256_GCM,data:wJecHLsNrpMgMXWvDJ8UBSCCDofqQpDc5oOWETR3lcej/O3CYXGS+HaiCiMlE9SJ5kI=,iv:hBgWeks0AzYWtuY8Wz5FxOOExRZBDVJktDLuk+8Vs8c=,tag:mhMBH019Wel88UfYywGljw==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:pWFY12MaY/3WBOdis7V9FSkrG959Mmr7t7qaaRl6,iv:faPw9A32P39FHKzrTCB21WPGROWtiAWcfhhvjIpRZnk=,tag:q8ryuGx4GJAeAJQOLe+Amg==,type:str]
    mariadb-database: ENC[AES256_GCM,data:miOwcr++mSUsBw==,iv:NhkTrcXO6Tbqnhko/ZaNpSOO0xhx58zqUyTSSY7/WoY=,tag:T0yZz7KtwX01bE+hcvmkmg==,type:str]
    mariadb-user: ENC[AES256_GCM,data:apOvsrmNBjPTmw==,iv:S54y7F1poFrjkPe/EQz9mCAeFChfA1mUFcIn1G+l3Jw=,tag:4Zhbbm2KKx7kFd8bUsJkQA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:u6sots997sjreRwfJl7oXqzQXAuAz7HGCJaxFGOu,iv:XawmSq5iV4Go5iOysFB9QyopKZMK2PeXnOs3qguYeW8=,tag:vR13FfkuDqp4Vy53TDVjnQ==,type:str]
    redis-password: ENC[AES256_GCM,data:aWYZuTelw+QOlRUPRVeNRxP4cI8Rx77QsvqovFVk,iv:9975ZBOgFU15W8SErIkGf4f4e2iU3RYBslv87mUBrOk=,tag:gJolR5bqSiqHGEZOnw22Ng==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:CQz4uhZ8L73EsEl21PSMWzMyanJi8Aye0pQhrTEs,iv:4+pdqO/04Ybx++IwokorprW3W58YDjAO1LPh2Fz96Fk=,tag:ZnvbJDSHWDZfundNVPyfVA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:6QlZ/5gtDglBCsLUUGEmwFGU8pAjIXovRPysEltKxVmz1l49wc5IM+RPBJONY6GXU9wA49RZI4WEnf0u4Wo3KA==,iv:DLZFGXOLW2BJZntCFctfLvs6XstCC2XOmrdt1DjF+ZU=,tag:xIyDQfIDp/lu5CraB+6AcQ==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:10cWJ3XOuOzBrXfTn3Mx9kCjUg==,iv:n6wSZ9ZTXUloN5bIyhpDetHsCoAnykf898UhL6TJKmk=,tag:/UmO61sbHrrD8r+c9491QQ==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:4xubZmVQVlAVKnxPvTr395Kxxlp7sMeDaV5n5WZf4IA=,iv:d6Maq2I5MVTN9tdwbO5f2N0eNNX52wbEOJhnQiXHNSs=,tag:cZaQnlVq8G2Pw/SnHmkV5w==,type:str]
sops:
    age:
        - recipient: age12qymzd9yg0w68wwfyfrhsc2r5zkxxzp8a4yck960xp9uxsvmwchqyzj8lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK0xKQUd4ZHJ5anlpRlcw
            Q0FNUVBQN2RkcWRpVm9vOCt5MERCZm9IMHhJClZtSmR5OUtjVis1NHpMNVQ1QVhB
            MXBmYW9VR1h3bkdUU01tUlVaa0t6RGsKLS0tIDFtWnN0NjdlbDJsSjFwa3ZvdXlj
            QW43VkpKTDNNN1JTbTExczU3TjdoSjQKL20oYFI9AbHbVR+wyLNzBGBv1Z+Pn7tx
            C4iubCaeAZssHpNjGrJSDzNuK9UCUUMdb3h08gNTSYw3SwQDGKdkUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T13:25:14Z"
    mac: ENC[AES256_GCM,data:L6L18OIpD+18dbqBCEu7E7S2kYuRYtpEkYvlI0oj+lcYZneonxnFrkxdP986wRRFAkc6MrK7M1d86WdPQbIf9Y/7qBLoCvLbhZRiPUsrAIhv7PM3BJI7E8djKK2txchWGlcW3mSY+ufeKJYD0z5XgKmGLklbSX3CbsSNKPQD1hU=,iv:Il2VsF0uzjDnZ3bAr4g+PkERg1SiqqYJDSkpZ2P27VU=,tag:KALn1iBZSM6L/i553zgA9w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: anicord-webserver
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:y44PG1TNsjT5EXKElGIAtV6eQMMK8h64ItAfGqiCf2BXvwk9J3OXk77bWPWutrh5+TWBTKa2GFxL8+j9kVLzG4GHZp3kzMjQWPLuw9Ly8RVD/aDNNo3jeO68bP+D9Ic5W0Fz6K/8cYdcZW0nvxN5sgJQJoqVyBd8Xas4F21zaK9+e+yTRQ==,iv:v/1R0HKgBIiiBxBHXX6w8asCU7H27BRK/SMCLxJ+OWY=,tag:fWRpApk94USqI6258y41Kg==,type:str]
sops:
    age:
        - recipient: age12qymzd9yg0w68wwfyfrhsc2r5zkxxzp8a4yck960xp9uxsvmwchqyzj8lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK0xKQUd4ZHJ5anlpRlcw
            Q0FNUVBQN2RkcWRpVm9vOCt5MERCZm9IMHhJClZtSmR5OUtjVis1NHpMNVQ1QVhB
            MXBmYW9VR1h3bkdUU01tUlVaa0t6RGsKLS0tIDFtWnN0NjdlbDJsSjFwa3ZvdXlj
            QW43VkpKTDNNN1JTbTExczU3TjdoSjQKL20oYFI9AbHbVR+wyLNzBGBv1Z+Pn7tx
            C4iubCaeAZssHpNjGrJSDzNuK9UCUUMdb3h08gNTSYw3SwQDGKdkUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T13:25:14Z"
    mac: ENC[AES256_GCM,data:L6L18OIpD+18dbqBCEu7E7S2kYuRYtpEkYvlI0oj+lcYZneonxnFrkxdP986wRRFAkc6MrK7M1d86WdPQbIf9Y/7qBLoCvLbhZRiPUsrAIhv7PM3BJI7E8djKK2txchWGlcW3mSY+ufeKJYD0z5XgKmGLklbSX3CbsSNKPQD1hU=,iv:Il2VsF0uzjDnZ3bAr4g+PkERg1SiqqYJDSkpZ2P27VU=,tag:KALn1iBZSM6L/i553zgA9w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
