apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: webserver
        image: ghcr.io/anicord-acow/webserver@sha256:edd13393fd24fe1af066c5f437bf834278f2c4bdb065f0051ccbfd7194dd65a5
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: MYSQL
        - name: REDIS
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: REDIS
        - name: ORIGIN
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: ORIGIN
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: DISCORD_CLIENT_ID
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: DISCORD_CLIENT_SECRET
        - name: JWT_PRIVATE_KEY_PATH
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: JWT_PRIVATE_KEY_PATH
        - name: JWT_PUBLIC_KEY_PATH
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: JWT_PUBLIC_KEY_PATH
        volumeMounts:
          - name: keys
            mountPath: /app/keys
            readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: keys

---

apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 13000
  selector:
    app: webserver
