apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: webserver
        image: ghcr.io/anicord-acow/webserver@sha256:0320e3475b431a4523a8597bd636537a68c10ee8ade94840f19e57a1481a0330
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: MYSQL
        - name: BETTER_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: BETTER_AUTH_SECRET
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: DISCORD_CLIENT_ID
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: DISCORD_CLIENT_SECRET
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: REDIS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 13000
  selector:
    app: webserver
